### ISSUE TITLE
Two opengl calls in GUI.cpp are only supported by Nvidia cards

### ISSUE THREAD

**Issue by amarburg** [amarburg/lsd_slam#14]
Got this as a comment from the blog:

> RE:I was having problems with OpenGL error 1280
> 
> –> Two opengl calls in GUI.cpp are only supported by Nvidia cards; others cause errors. You can safely comment out these two lines:
> 
> void GUI::drawKeyframes()
> glHint(GL_MULTISAMPLE_FILTER_HINT_NV, GL_NICEST);
> 
> void GUI::postCall()
> glGetIntegerv(GL_GPU_MEM_INFO_CURRENT_AVAILABLE_MEM_NVX, &cur_avail_mem_kb);

**Comment by freedick** [comment]
I was also getting lots of 1280 from LSD_GUI, and and I can confirm that commenting those lines out made the 1280 errors dissappear. I am still getting "not available with non-pangolin window" from SwapBuffers and ProcessEvents. My window does not output anything.

I am running 16.10 inside VMWare so that may be the largest issue.

**Comment by freedick** [comment]
I am getting the same problem on an Intel(R) Kabylake GT2 on Ubuntu 16.04. An endless flow of the following two messages:
```
SwapBuffers: Not available with non-pangolin window.
ProcessEvents: Not available with non-pangolin window.
```

**Comment by amarburg** [comment]
I've had some weird regressions lately with the GUI (thought I've mostly been testing on my Mac).   I think the Pangolin-GLUT tools have evolved out from under us.   Should have some time to investigate this week.

**Comment by amarburg** [comment]
To follow up, I had a bit of time to look at this.   Architecturally, I think the right solution was to become less dependent on the GLUT mode of Pangolin and instead let its abstraction do the work for us, building windows native to the platform.

By making this happen, I was able to drop the dependency on my patched Pangolin and go back to Steven Lovegrove's upstream branch (less one patch to squelch that OpenGL 1280 error on OS X).

The transition isn't perfect, the "live video" image in the GUI is not currently working, but it is far less of a pain to compile than before.

If recompiling, be sure to remove any existing "Pangolin" directories (build-{Debug,Release}/Pangolin) to ensure the non-force-GLUT version is built)
