### ISSUE TITLE
Add Eigen3 as system library

### ISSUE THREAD

**Issue by FirefoxMetzger** [amarburg/lsd_slam#16]
While compiling the project with warning `-Wignored-attributes` Eigen3 turns into a very ... very chatty library. It makes it unnecessarily hard to spot actual compile errors.

Adding it as a system library like

    set( LSDSLAM_INCLUDE_DIRS                                                                 
    ${CMAKE_SOURCE_DIR}/lib                                                               
    ${CMAKE_SOURCE_DIR}/lib/lsd_core                                                      
    ${OpenCV_INCLUDE_DIRS}                                                                
    ${Boost_INCLUDE_DIR}                                                                  
    ${Pangolin_INCLUDE_DIRS}                                                              
    ${PROJECT_SOURCE_DIR}/thirdparty/Sophus                                               
    ${G2O_INCLUDE_DIR}                                                                    
    SYSTEM ${EIGEN3_INCLUDE_DIR} )   

in the top level `CMakeLists.txt` stops Eigen3 from printing warnings. This makes the build process much cleaner.

**Comment by amarburg** [comment]
At the warnings from g2o the deprecation warning about "AlignedBit"?

**Comment by FirefoxMetzger** [comment]
/home/user/lsd_slam/lib/util/SophusUtil.h:72:31:   required from here
    /usr/include/eigen3/Eigen/src/Core/DenseCoeffsBase.h:55:30: warning: ignoring attributes on template 
    argument ‘Eigen::internal::packet_traits<float>::type {aka __vector(8) float}’ [-Wignored-attributes]

or

    /home/user/lsd_slam/lib/util/SophusUtil.h:72:31:   required from here
    /usr/include/eigen3/Eigen/src/Core/util/XprHelper.h:130:44: warning: ignoring attributes on template argument ‘Eigen::internal::unpacket_traits<__vector(8) float>::half {aka __vector(4) float}’ [-Wignored-attributes]

These are examples of warnings I am getting when compiling with eigen3 as a normal library for LSD-SLAM. Those would get suppressed when compiling LSD-SLAM.

The warnings during g2o compilation are not affected by this. g2o is compiled as external project and thus gets it's own set of compile flags. It is including eigen3 as a normal dependancy (-I vs -isystem as a compile flag) and will still throw mentioned warning.

**Comment by amarburg** [comment]
Ah, ok.   I don't fully understand the ramifications of marking the include directory "system" but it seems harmless.  I will make the change and test.

**Comment by amarburg** [comment]
Made the change in bdc3282

**Comment by FirefoxMetzger** [comment]
https://gcc.gnu.org/onlinedocs/cpp/System-Headers.html

Here is the corresponding part of the GCC documentation about system headers.

**Comment by amarburg** [comment]
Ah, got it, thanks.
