### ISSUE TITLE
make dep g3log problem

### ISSUE THREAD

**Issue by Kay1794** [amarburg/lsd_slam#18]
`[ 28%] Performing patch step for 'g3log'
patching file CMakeLists.txt
Hunk #1 FAILED at 72.
1 out of 1 hunk FAILED -- saving rejects to file CMakeLists.txt.rej
make[3]: *** [g3log/src/g3log-stamp/g3log-patch] Error 1
make[2]: *** [CMakeFiles/g3log.dir/all] Error 2
make[1]: *** [CMakeFiles/deps.dir/rule] Error 2
make: *** [deps] Error 2
`

Does anyone meet the same problem?

**Comment by alessandroTorresani** [comment]
I have the same problem. Xubuntu 16.04. Have you found a solution?

**Comment by amarburg** [comment]
Hm, let me look today.

**Comment by alessandroTorresani** [comment]
Thank you sir. Your help and your work are really appreciated.

**Comment by amarburg** [comment]
I believe commit 587e5b0 resolves this on Unix.  I am still not able to compile due to an upstream change on g2o....

**Comment by amarburg** [comment]
Commit 1f79f9 resolves the g2o problems.
