### ISSUE TITLE
openCV undefined reference

### ISSUE THREAD

**Issue by alessandroTorresani** [amarburg/lsd_slam#19]
Hi,
I got this error when executing the make command, although the cmake command gave any error about openCV.

CMakeFiles/LSD_GUI.dir/ParseArgs.cpp.o: In function `cv::String::~String()':
ParseArgs.cpp:(.text._ZN2cv6StringD2Ev[_ZN2cv6StringD5Ev]+0x14): undefined reference to `cv::String::deallocate()'
CMakeFiles/LSD_GUI.dir/ParseArgs.cpp.o: In function `cv::String::String(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&)':
ParseArgs.cpp:(.text._ZN2cv6StringC2ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE[_ZN2cv6StringC5ERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE]+0x69): undefined reference to `cv::String::allocate(unsigned long)'
CMakeFiles/LSD_GUI.dir/ParseArgs.cpp.o: In function `lsd_slam::ImagesSource::getImage(int, cv::Mat&)':
ParseArgs.cpp:(.text._ZN8lsd_slam12ImagesSource8getImageEiRN2cv3MatE[_ZN8lsd_slam12ImagesSource8getImageEiRN2cv3MatE]+0xc4): undefined reference to `cv::imread(cv::String const&, int)'
../lib/liblsdslam.a(SlamSystem.cpp.o): In function `cv::String::operator=(cv::String const&)':
SlamSystem.cpp:(.text._ZN2cv6StringaSERKS0_[_ZN2cv6StringaSERKS0_]+0x28): undefined reference to `cv::String::deallocate()'
../lib/liblsdslam.a(DepthMap.cpp.o): In function `cv::String::String(char const*)':
DepthMap.cpp:(.text._ZN2cv6StringC2EPKc[_ZN2cv6StringC5EPKc]+0x4d): undefined reference to `cv::String::allocate(unsigned long)'
../lib/liblsdslam.a(DepthMap.cpp.o): In function `cv::Mat::Mat(int, int, int, void*, unsigned long)':
DepthMap.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x130): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
DepthMap.cpp:(.text._ZN2cv3MatC2EiiiPvm[_ZN2cv3MatC5EiiiPvm]+0x237): undefined reference to `cv::error(int, cv::String const&, char const*, char const*, int)'
../lib/liblsdslam.a(DepthMap.cpp.o): In function `lsd_slam::DepthMap::doLineStereo(float, float, float, float, float, float, float, lsd_slam::Frame const*, float const*, float&, float&, float&, lsd_slam::RunningStats*)':
DepthMap.cpp:(.text._ZN8lsd_slam8DepthMap12doLineStereoEfffffffPKNS_5FrameEPKfRfS6_S6_PNS_12RunningStatsE[_ZN8lsd_slam8DepthMap12doLineStereoEfffffffPKNS_5FrameEPKfRfS6_S6_PNS_12RunningStatsE]+0x29ed): undefined reference to `cv::line(cv::_InputOutputArray const&, cv::Point_<int>, cv::Point_<int>, cv::Scalar_<double> const&, int, int, int)'
../lib/liblsdslam.a(globalFuncs.cpp.o): In function `lsd_slam::printMessageOnCVImage(cv::Mat&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
globalFuncs.cpp:(.text+0x4cc): undefined reference to `cv::putText(cv::_InputOutputArray const&, cv::String const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
globalFuncs.cpp:(.text+0x5ce): undefined reference to `cv::putText(cv::_InputOutputArray const&, cv::String const&, cv::Point_<int>, int, double, cv::Scalar_<double>, int, int, bool)'
../lib/liblsdslam.a(KeyFrameGraph.cpp.o): In function `lsd_slam::KeyFrameGraph::dumpMap(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >)':
KeyFrameGraph.cpp:(.text+0xabd): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
KeyFrameGraph.cpp:(.text+0xc55): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
KeyFrameGraph.cpp:(.text+0xe1f): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
../lib/liblsdslam.a(ImageDisplay_OpenCV.cpp.o): In function `lsd_slam::Util::displayThreadLoop()':
ImageDisplay_OpenCV.cpp:(.text+0x109): undefined reference to `cv::namedWindow(cv::String const&, int)'
ImageDisplay_OpenCV.cpp:(.text+0x15e): undefined reference to `cv::resizeWindow(cv::String const&, int, int)'
ImageDisplay_OpenCV.cpp:(.text+0x1d1): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
../lib/liblsdslam.a(ImageDisplay_OpenCV.cpp.o): In function `lsd_slam::Util::displayImage(char const*, cv::Mat const&, bool)':
ImageDisplay_OpenCV.cpp:(.text+0x42c): undefined reference to `cv::namedWindow(cv::String const&, int)'
ImageDisplay_OpenCV.cpp:(.text+0x47d): undefined reference to `cv::resizeWindow(cv::String const&, int, int)'
ImageDisplay_OpenCV.cpp:(.text+0x538): undefined reference to `cv::imshow(cv::String const&, cv::_InputArray const&)'
../lib/liblsdslam.a(Sim3Tracker.cpp.o): In function `lsd_slam::Sim3Tracker::calcResidualAndBuffers_debugFinish(int)':
Sim3Tracker.cpp:(.text+0x54ef): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
Sim3Tracker.cpp:(.text+0x55c8): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
Sim3Tracker.cpp:(.text+0x56a1): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
../lib/liblsdslam.a(SE3Tracker.cpp.o): In function `lsd_slam::SE3Tracker::calcResidualAndBuffers_debugFinish(int)':
SE3Tracker.cpp:(.text+0x37cc): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
SE3Tracker.cpp:(.text+0x38a5): undefined reference to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)'
../lib/liblsdslam.a(SE3Tracker.cpp.o):SE3Tracker.cpp:(.text+0x397e): more undefined references to `cv::imwrite(cv::String const&, cv::_InputArray const&, std::vector<int, std::allocator<int> > const&)' follow
collect2: error: ld returned 1 exit status
tools/CMakeFiles/LSD_GUI.dir/build.make:254: recipe for target 'LSD_GUI' failed
make[2]: *** [LSD_GUI] Error 1
CMakeFiles/Makefile2:305: recipe for target 'tools/CMakeFiles/LSD_GUI.dir/all' failed
make[1]: *** [tools/CMakeFiles/LSD_GUI.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

My openCV 2.4.13.4 installation folder is /usr/local/include for headers, and /usr/local/lib for libraries.

**Comment by amarburg** [comment]
Hmm.  What distribution are you using?   

All of the missing functions take "String" arguments, which starts to feel like a [libc4 versus libc5 string implmentation problem](https://gcc.gnu.org/onlinedocs/libstdc++/manual/using_dual_abi.html)

**Comment by alessandroTorresani** [comment]
I'm using Xubuntu 16.04.3.

This is the output of the command "uname -a":
Linux harwin-VirtualBox 4.10.0-40-generic #44~16.04.1-Ubuntu SMP Thu Nov 9 15:37:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux.

My g++ version is 
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.5) 5.4.0 20160609

What can I do to provide you more information about this libc4 vs libc5 problem?

**Comment by alessandroTorresani** [comment]
Solved, I recompiled OpenCV 3.0 instead of 2.4 and it works.
