### ISSUE TITLE
Build error with lcsparse

### ISSUE THREAD

**Issue by Arsakes** [amarburg/lsd_slam#4]
In final stages of compilation the compiler is trying to link 
`-lcsparse
`which isn't set anywhere in the cmake options.
In my case the CSPARSE_LIBRARY option in CMAKE is `/usr/lib/libcxsprase.so`
therefore parametr passed to linker should be:
`-lcxsparse
`

In `/lib/lsd_core/CMakeLists.txt` you explicitely set to link csparse instead of cxsparse in case used platform is linux - my case cleary show - that it isn't a good way to go.

**Comment by amarburg** [comment]
Thanks.   I believe I am correctly pulling in the right libraries for g2o now.
