### ISSUE TITLE
Please include glm as required libarary

### ISSUE THREAD

**Issue by Arsakes** [amarburg/lsd_slam#5]
I'm using ArchLinux, build failed at first due to the fact
glm library wasn't installed.
Would be wise to ensure cmake checks for it.

**Comment by amarburg** [comment]
I think this is a dependency for Pangolin and it should check for it.   But I'll see what's involved in including it as a check.

**Comment by amarburg** [comment]
I've restructured the CMakefiles to build a local copy of Pangolin by default.  When this happens, it does check for glm, glew, and glut.    However, if you're using a copy of Pangolin you install yourself, you (or Pangolin) are responsible for the dependencies.
